#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color     "#26F0F1"
bspc config normal_border_color      "#202A25"

# Staring wallpaper manager
nitrogen --restore &
picom &

# Adding the polybar
$HOME/.config/polybar/launch.sh
bspc rule -a "Microsoft Teams - Preview" desktop='^5'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled

# Adding a screensaver sflock
xss-lock --transfer-sleep-lock -- sflock &

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
# Update: nm-applet replaced by networkmanager_dmenu and pa-applet incorporated
# into the polybar
#nm-applet & 
#pa-applet &
blueman-applet &

# start-up applications
megasync &
nextcloud &
nixnote2 &
teams &
onedrive --monitor &
keepassxc &

#for battery
xfce4-power-manager &

# Fix the cursor default
# https://www.reddit.com/r/bspwm/comments/8gwwlc/cursor_displays_x_when_not_over_window/dyfj6cw?utm_source=share&utm_medium=web2x&context=3
# https://wiki.archlinux.org/index.php/Cursor_themes#Change_X_shaped_default_cursor
xsetroot -cursor_name left_ptr &

