#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

#Check available monitors
#Replace variable to your own monitor
#check with xrandr -q | grep -w connected
MONITOR_NAME="eDP-1"
EXTERNAL_MONITOR_NAME="HDMI-1"

STATUS_EXTERNAL_MONITOR=$(xrandr --query | grep $EXTERNAL_MONITOR_NAME)
if [[ $STATUS_EXTERNAL_MONITOR = *connected* ]]; then
    xrandr --output $MONITOR_NAME --primary --mode 1366x768  --output $EXTERNAL_MONITOR_NAME --mode 1920x1080 --rotate normal --right-of $MONITOR_NAME
fi

#Set according to presence of external monitor
if [[ $STATUS_EXTERNAL_MONITOR = *connected* ]]; then
	bspc monitor $MONITOR_NAME -d 1 2 3 4 5
	bspc monitor $EXTERNAL_MONITOR_NAME -d 6 7 8 9 10
else
	bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color     "#26F0F1"
bspc config normal_border_color      "#202A25"

# Staring wallpaper manager
nitrogen --restore &
picom &
#rofi -no-lazy-grab -show drun -modi drun &

# Adding the polybar according to monitors
if [[ $STATUS_EXTERNAL_MONITOR = *connected* ]]; then
	$HOME/.config/polybar/launch_two.sh
else
	$HOME/.config/polybar/launch.sh
fi

bspc rule -a "Microsoft Teams - Preview" desktop='^5'
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a discord desktop='^7' 
bspc rule -a Thunderbird desktop='^6' 
bspc rule -a Slack desktop='^9' 
bspc rule -a Rambox desktop='^4' 
bspc rule -a Chromium desktop='^2'
bspc rule -a Brave-browser desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a ksnip state=floating

# Adding a screensaver sflock
xss-lock --transfer-sleep-lock -- sflock &

# NetworkManager is the most popular way to manage wireless networks on Linux,
# and nm-applet is a desktop environment-independent system tray GUI for it.
# Update: nm-applet replaced by networkmanager_dmenu and pa-applet incorporated
# into the polybar
#nm-applet & 
#pa-applet &
blueman-applet &

# start-up applications
megasync &
nextcloud &
nixnote2 &
teams &
onedrive --monitor &
python3 /opt/thefanclub/overgrive/overgrive &
slack &
discord &
birdtray &
rambox &
keepassxc &

#for battery
xfce4-power-manager &

# Fix the cursor default
# https://www.reddit.com/r/bspwm/comments/8gwwlc/cursor_displays_x_when_not_over_window/dyfj6cw?utm_source=share&utm_medium=web2x&context=3
# https://wiki.archlinux.org/index.php/Cursor_themes#Change_X_shaped_default_cursor
xsetroot -cursor_name left_ptr &

